declare const styles: {
  readonly "button": string;
  readonly "videoPlayer": string;
  readonly "title": string;
  readonly "videoConteiner": string;
  readonly "video": string;
  readonly "controlsPlayer": string;
  readonly "controls": string;
  readonly "controlButton__play": string;
  readonly "controlButton": string;
  readonly "timeControls": string;
  readonly "timeBar": string;
  readonly "timeBar_progress": string;
  readonly "time": string;
  readonly "progressTime": string;
  readonly "allTime": string;
  readonly "controlsButtons": string;
  readonly "controls_rewind": string;
  readonly "rewindButton": string;
  readonly "controls_volume": string;
  readonly "volumeButton": string;
  readonly "volumeBar": string;
  readonly "volumeBar_current": string;
  readonly "controls_options": string;
  readonly "optionsButton": string;
  readonly "settingsButton": string;
  readonly "screenButton": string;
};
export = styles;

